### ISSUE TITLE
Always giving me StatusCodeError: 403 - ""

### ISSUE THREAD

**Issue by ryuujo** [philbot9/youtube-info#37]
Sometimes I need to re-fetch it again and again and takes more than 10 times re-fetching until I can get the data properly. And it's totally annoying since I use this data to get video title
![image](https://user-images.githubusercontent.com/41565025/86080429-13ae5980-babd-11ea-9631-b19d76ac1df7.png)

**Comment by FBIMiro** [comment]
Experiencing the same thing

**Comment by APKiwi** [comment]
Also experiencing the same thing

**Comment by ryuujo** [comment]
Is it possible that the code now deprecated? I see no updates since last 2 years

**Comment by skzap** [comment]
Same

**Comment by skzap** [comment]
Changing the user-agent to 'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)' in lib/fetch-page.js fixed the issue for me. Somehow wish we could pass the User-Agent option directly from the fetchVideo(id, opts)

**Comment by jbernar3** [comment]
Changing the user-agent to that worked for me as well.  I found it in index.js.

**Comment by udhayakumaran** [comment]
Changing the user-agent works for me as well

**Comment by TheMonDon** [comment]
Changing the user agent worked for a day for me but now it stopped working

**Comment by lollka** [comment]
I used this hotfix, still works for me, using default user-agent:
```javascript
/* return fetchCommentCount(videoId, sessionToken, commentToken).then(function (
      commentCount
    ) {
      videoInfo.commentCount = commentCount */
      return videoInfo
    //})
```
I commented/removed lines 28-31 and 32, leaving only "return videoInfo" in index.js, because it looks like fetching comment count via "https://www.youtube.com/watch_fragments_ajax" doesn't work anymore. And this caused to return error 403 for me.

Edit:
If you need video author, change:
```javascript
var owner = $('.yt-user-info > a').text()
```
To this:
```javascript
var owner = body.split('\"author\":\"')[1].split('","')[0]
```
In line 115.

**Comment by jay-edxx** [comment]
I found the same issue. 
Problem: In index.js file, when it tries to execute **fetchCommentCount**(which will fetch the comment count.), causes an error of 403.

**Comment by Jaysojitra13** [comment]
I faced the same issue of status code 4:
Problem: In index.js file, When it tries to run **fetchCommentCount**(which calculate the comment count), causes an error of 403.

**Comment by macedonga** [comment]
Same

**Comment by kylerchin** [comment]
```
dQw4w9WgXcQ
Unhandled rejection Error: StatusCodeError: 403 - ""
    at /home/disrupt/discordbots/Adora-Bot/node_modules/youtube-info/index.js:101:15
    at tryCatcher (/home/disrupt/discordbots/Adora-Bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/disrupt/discordbots/Adora-Bot/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/disrupt/discordbots/Adora-Bot/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/disrupt/discordbots/Adora-Bot/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/disrupt/discordbots/Adora-Bot/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/disrupt/discordbots/Adora-Bot/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/disrupt/discordbots/Adora-Bot/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/disrupt/discordbots/Adora-Bot/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/disrupt/discordbots/Adora-Bot/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

Still broken for me
